### ISSUE TITLE
Some improvements.

### ISSUE THREAD

**Issue by ghost** [mgee/slimline#15]
Hey Markus, was thinking recently about some inconsistency in a way slimline displays data. pythonenv would end up in brackets in RPROMPT, AWS profile would be 'nude' (without brackets) in left prompt.

I was wondering whether some order and possibly configuration options for 'sections' could be introduced.

Mainly this is because I would like to see some extra, optional features like kubernetes cluster information. (Since it involves external command call it would be great if it could be done asynchronously like git.)

Also, would be amazing if sections could be configurable, order and position (left or right prompt) as well as separator between them.

Another thing is:
**prompt_slimline_set_prompt** uses function calls to retrieve sections while
**prompt_slimline_set_rprompt** has all/some code embedded.
I could see all **if** statements going into their relevant functions since calls are very inexpensive.

It's all really to clean things up a bit to allow easier sections development.

What do you think?

**Comment by mengelbrecht** [comment]
Indeed it would be nice to be able to configure the order of the sections and their format. However, I do not want to add too much complexity to the prompt theme. Maybe I come up with a good idea later...

To address the inconsistency between AWS profile and pythonenv the AWS profile could also be in parenthesis with a configurable color. What do you think?

Regarding the prompt/rprompt function call difference I just pushed some commits which clean that up.

**Comment by ghost** [comment]
Perfect, thanks!

(I am still seeing trailing space at the end of RPROMPT.)

Next step would be, I guess, to provide configuration for displayed sections.

I would see it as:

    prompt_slimline_left_prompt=(user_host_info cwd symbol)
    prompt_slimline_right_prompt=(exit_status execution_time git aws_profile virtualenv)

    prompt_slimline_section_separator=', ', or ' | ', or ' - '…
(or even different separators for left and right prompts)

(Names are obviously just examples.)

Above could replace all `SLIMLINE_DISPLAY_*` variables. Section functions would not need to check whether they have to return data, as they always should if called.
I think it could be achieved by looping through array and calling `prompt_slimline_section_<SECTION_NAME>` functions which then return value. That could be actually passed through helper function which would add separator should output be non-empty.

How does it all sound?

On the other note: there are two instances of `$(whoami)` which could be replaced with `$USER`. Is there advantage for running `whoami`?

**Comment by mengelbrecht** [comment]
The trailing space you are seeing is probably the RPROMPT indent as described [here](https://superuser.com/questions/655607/removing-the-useless-space-at-the-end-of-the-right-prompt-of-zsh-rprompt). It can be removed by setting `ZLE_RPROMPT_INDENT=0`, but this may have side effects in some terminals.

There was no special reason I used `whoami` instead of `$USER`. I pushed a commit to change it to `$USER`. Since this is a builtin variable it might improve performance.

Currently I am thinking of a way of combining your section idea with the format customization flexibility as implemented in [gitline](https://github.com/mgee/gitline). In any case I do not want to break backwards compatibility of the current options. Instead I would implement the new features in a slimline2 prompt theme (which could be part of this repository).

**Comment by mengelbrecht** [comment]
@katsika With the work done in #16 it will be super easy to add a custom prompt section with asynchronous command execution. Stay tuned.

**Comment by ghost** [comment]
It's not „some” any more! Thank you! Had a look through commits in PR and it all looks very nice, good job!

**Comment by mengelbrecht** [comment]
Done with the merge of #16.

**Comment by ghost** [comment]
Awesome, well done! Thanks!
